# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, doc_uri=None):  # noqa: E501
        """DocumentRequest - a model defined in Swagger

        :param doc_uri: The doc_uri of this DocumentRequest.  # noqa: E501
        :type doc_uri: str
        """
        self.swagger_types = {
            'doc_uri': str
        }

        self.attribute_map = {
            'doc_uri': 'docURI'
        }

        self._doc_uri = doc_uri

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The documentRequest of this DocumentRequest.  # noqa: E501
        :rtype: DocumentRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def doc_uri(self):
        """Gets the doc_uri of this DocumentRequest.


        :return: The doc_uri of this DocumentRequest.
        :rtype: str
        """
        return self._doc_uri

    @doc_uri.setter
    def doc_uri(self, doc_uri):
        """Sets the doc_uri of this DocumentRequest.


        :param doc_uri: The doc_uri of this DocumentRequest.
        :type doc_uri: str
        """

        self._doc_uri = doc_uri
