# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DocumentsRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, doc_ur_is=None):  # noqa: E501
        """DocumentsRequest - a model defined in Swagger

        :param doc_ur_is: The doc_ur_is of this DocumentsRequest.  # noqa: E501
        :type doc_ur_is: List[str]
        """
        self.swagger_types = {
            'doc_ur_is': List[str]
        }

        self.attribute_map = {
            'doc_ur_is': 'docURIs'
        }

        self._doc_ur_is = doc_ur_is

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The documentsRequest of this DocumentsRequest.  # noqa: E501
        :rtype: DocumentsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def doc_ur_is(self):
        """Gets the doc_ur_is of this DocumentsRequest.


        :return: The doc_ur_is of this DocumentsRequest.
        :rtype: List[str]
        """
        return self._doc_ur_is

    @doc_ur_is.setter
    def doc_ur_is(self, doc_ur_is):
        """Sets the doc_ur_is of this DocumentsRequest.


        :param doc_ur_is: The doc_ur_is of this DocumentsRequest.
        :type doc_ur_is: List[str]
        """

        self._doc_ur_is = doc_ur_is
